### PR TITLE
updated to 3.6.10

### PR DESCRIPTION
**Pull request by dereuromark**
works like a charm :)

### CODE REVIEW

**Comment by Hyra** [comment]
Awesome ! Can't pull automatically though, so i'll have to manually merge it in somehow :)

Btw, I noticed when installing phpunit into app/Vendor instead of Vendor the 2 Autoload files need a prefix in the require statements for cake to find the files correctly

**Comment by dereuromark** [comment]
ah interesting :)
I just "installed" to app/ temporally for testing before - so I never really noticed...
only used the root vendors folder

how does the prefix looks like?

**Comment by Hyra** [comment]
Instead of:

require_once 'File/Iterator/Autoload.php';

you do:

require_once APP.'Vendor/File/Iterator/Autoload.php';

But only in case you install it to app/Vendor, obviously :)

**Comment by dereuromark** [comment]
i see
wouldnt it also work to add this at the top (or in any file before that): 

```
set_include_path(get_include_path().PATH_SEPARATOR.dirname(__FILE__));
```

**Comment by Hyra** [comment]
Strange, PHPUnit wouldn't work unitl i added the path prefix.
Now, when i remove those prefixes, it still works.

Need to investigate that.

Your idea sounds better, would be easy to integrate in the installer as well :)

**Comment by Hyra** [comment]
Hey Mark,

Finally got around to manually merge your changes. They are done!

Thanks again buddy.

**Pull request merged**
